name: Transfer Repo

on: [workflow_dispatch]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-18.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up transfer file
      env:
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        echo $APPLE_TEAM_ID >> file.txt

    - name: Copy file
      run: aws s3 cp file.txt s3://sn-mobile-transfer/file.txt